// PROTOTYPE CODE, ACTUAL CODE IS COMMENTED SCROLL DOWN PAST ALL THE UNCOMMENTED CODE
const data = `        
\x3Cscript xmlns="http://www.standardnine.com/s9ml" type="text/xml+s9ml" title="389d86174f3c4253b8c73cb709327dc9" class="s9-definition">

  <term key="389d86174f3c4253b8c73cb709327dc9">Program input</term>
  <definition>
    <title> Program input </title>
  <text> 
    Data sent to a computer for processing by a program. Input can come in a variety of forms, such as tactile, audio, visual, or text.&#160;
  </text>
  </definition>
\x3C/script>

\x3Cscript xmlns="http://www.standardnine.com/s9ml" type="text/xml+s9ml" title="Python+terminal" class="s9-definition">
  <term key="Python terminal">Python terminal</term>
  <definition>
      <title>Python terminal</title>
      
      <text>

          The window that displays textual output generated by
          <i>Python's</i>
          <i>print</i>
          statement. The terminal also allows the user to type commands that are immediately executed upon pressing the Enter key.
      
        </text>
  </definition>
\x3C/script>

\x3Cscript xmlns="http://www.standardnine.com/s9ml" type="text/xml+s9ml" title="c930e64f845d47bcac5ab02eac7413a7" class="s9-definition">
  <term key="c930e64f845d47bcac5ab02eac7413a7">expression</term>
  <definition>
      <title>expression</title>
      
      <text>
        &#160;A combination of variables, operators, or procedure calls that are evaluated and returns a single value.&#160;The evaluation of expressions follows a set order of operations defined by the programming language.
      </text>
  </definition>
\x3C/script>

\x3Cscript xmlns="http://www.standardnine.com/s9ml" type="text/xml+s9ml" title="db331c2f0a444bbab2cd78cfe677c87b" class="s9-definition">
  <term key="db331c2f0a444bbab2cd78cfe677c87b">substring</term>
  <definition>
      <title>substring</title>
      
      <text>
        part of an existing string
      </text>
  </definition>
\x3C/script>

\x3Cscript xmlns="http://www.standardnine.com/s9ml" type="text/xml+s9ml" title="e0cb7fa5eac74c8ca2bfe20633aea472" class="s9-definition">
  <term key="e0cb7fa5eac74c8ca2bfe20633aea472">code statement</term>
  <definition>
      <title>code statement</title>
      
      <text>
        A part of a program code that expresses an action to be carried out.&#160;
      </text>
  </definition>
\x3C/script>

\x3Cscript xmlns="http://www.standardnine.com/s9ml" type="text/xml+s9ml" title="input" class="s9-definition">
  <term key="input">input</term>
  <definition>
      <title>input</title>
      
      <text>
        Data that is given to an algorithm during the execution of a program and can affect the results of the algorithm.
      </text>
  </definition>
\x3C/script>

\x3Cscript xmlns="http://www.standardnine.com/s9ml" type="text/xml+s9ml" title="output" class="s9-definition">
  <term key="output">output</term>
  <definition>
      <title>output</title>
      
      <text>
        Data or actions produced by an algorithm. Including any data sent from a program to a device. Program output can come in a variety of forms, such as tactile, audio, visual, or text.
      </text>
  </definition>
\x3C/script>

\x3Cscript xmlns="http://www.standardnine.com/s9ml" type="text/xml+s9ml" title="runtime" class="s9-definition">
  <term key="runtime">runtime</term>
  <definition>
      <title>runtime</title>
      
      <text>
        The duration of time a program is executing, from start to finish.
      </text>
  </definition>
\x3C/script>

\x3Cscript xmlns="http://www.standardnine.com/s9ml" type="text/xml+s9ml" title="type" class="s9-definition">
  <term key="type">data type</term>
  <definition>
      <title>data type</title>
      
      <text>
        The kind&#160;of data being represented, such as a sequence of characters, an integer, or a true or false value, usually limiting the values allowed for the data.
      </text>
  </definition>
\x3C/script>

\x3Cscript xmlns="http://www.standardnine.com/s9ml" type="text/xml+s9ml" title="variable" class="s9-definition">
  <term key="variable">variable</term>
  <definition>
      <title>variable</title>
      
      <text>
        An abstraction inside the program that can hold a value. Each variable has associated data storage that represents one value at a time, but that value can be a list or other collection that in turn contains multiple values.&#160;&#160;
      </text>
  </definition>
\x3C/script>


`;

const finalTerms = [];
const finalDefinitions = [];

const rawScripts = data.split("/script>");

const scripts = rawScripts
  .filter((curScript) => curScript.trim() != "")
  .map((curScript) => curScript.trim());

scripts.forEach(function (curItem) {
  const rawDefinition = curItem.split("<definition>")[1];

  const term = rawDefinition.split("<title>")[1].split("</title>")[0].trim();

  const titleDefinition = rawDefinition
    .replaceAll("&#160;", " ")
    .replaceAll("<i>", " ")
    .replaceAll("</i>", " ");

  const definition = titleDefinition
    .split("<text>")[1]
    .split("</text>")[0]
    .trim();

  const finalDef = definition
    .split("\n")
    .filter((curScript) => curScript.trim() != "")
    .join(" ")
    .split(" ")
    .filter((curScript) => curScript.trim() != "")
    .join(" ");

  finalTerms.push(term);
  finalDefinitions.push(finalDef);
});

console.log(`Number of Vocab: ${finalTerms.length}`);
console.log(finalTerms.join("\n"));
console.log(finalDefinitions.join("\n"));

/*
IMPORTANT: RIGHT CLICK ON A VOCAB WORD AND CLICK INSPECT!!! 
Then go to the tab that says "console" and then paste the code in the console.

const data = document.querySelector("body > footer").innerHTML;
const finalTerms = [];
const finalDefinitions = [];

const rawScripts = data.split("/script>");

const scripts = rawScripts
  .filter((curScript) => curScript.trim() != "")
  .map((curScript) => curScript.trim());

scripts.forEach(function (curItem) {
  if(!curItem.includes('s9-remark')){      
    const rawDefinition = curItem.split("<definition>")[1];
    const term = rawDefinition.split("<title>")[1].split("</title>")[0].trim();

    const titleDefinition = rawDefinition
      .replaceAll("&#160;", " ")
      .replaceAll("<i>", " ")
      .replaceAll("</i>", " ");

    const definition = titleDefinition
      .split("<text>")[1]
      .split("</text>")[0]
      .trim();

    const finalDef = definition
      .split("\n")
      .filter((curScript) => curScript.trim() != "")
      .join(" ")
      .split(" ")
      .filter((curScript) => curScript.trim() != "")
      .join(" ");

    finalTerms.push(term);
    finalDefinitions.push(finalDef);
  }
});

console.log(`Number of Vocab: ${finalTerms.length}`);
console.log(finalTerms.join("\n"));
console.log(finalDefinitions.join("\n"));
*/
